name: Test design patterns

on:
  push:
    branches:
      - "main"
    paths:
      - "src/design-patterns/**"

jobs:
  test:
    name: Test latest changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with: 
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run test src/design-patterns/