name: Test data structures

on:
  push:
    branches:
      - "main"
    paths:
      - "src/data-structures/*"

jobs:
  test:
    name: Test latest changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with: 
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run test src/data-structures/